<!-- Исключительные ситуации (exception) - это ошибки, которые возникают в рантайме, то есть в 
момент запуска. Эти ошибки также как и синтаксические ошибки приводят к завершению нашей программы.
Но в отличие от синтаксических ошибок, эксепшены можно обрабатывать и заставить код выполняться
даже, если была такая ошибка. Инструкции в которых возможны исключения мы оборачиваем в блок
try. Если ошибка в блоке try проявляется, то моментально из блока try переходим в обработчик
этой ошибки, который находится в блоке catch. То есть ошибку ловим в try и обрабатываем
ее в блоке catch

-->

<script>
    // Пример №1
    // try{
    //     const TEST = 5;
    //     console.log(TEST);
    //     TEST = 10;//в этой инструкции будет ошибка
    //     let x = 1;
    //     alert(x);
    // }catch(error){
    //     console.log(error.name);//получили тип ошибки
    //     console.log('Нельзя изменять значение констант');//получили описание ошибки
    // }

    // console.log('Все ок')

    // Оператор throw позволяет генерировать ошибку

    // let count = 0;

    // while(1){
    //     let answer = +prompt('Введите значение от 1 до 10');
    //     if(answer < 1 || answer > 10){
    //         count++;
    //         if(count == 4){
    //             throw new SyntaxError('Попытки закончились!');
    //         }
    //         continue;
    //     }
    //     alert('Принято')
    //     break;
    // }

    // Если необходимо блок с инструкциями запускать независимо от того,
    // были ошибки или не были, используйте блок finally


    try{
        alert('try');
        if(confirm('Сгенерировать ошибку?')){
            BAD_CODE();
        }
    }catch(e){
        alert('catch сработал')
    }
    finally{
        alert('finally')
    }


</script>